config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  resources :users
  resources :stores

  match '/authenticate_user', :to => 'sessions#authenticate_user', :via => [:post], :as => :authenticate_user
  match '/authenticate_store', :to => 'sessions#authenticate_store', :via => [:post], :as => :authenticate_store

  get '/logout_user' => 'sessions#destroy_user', as: :logout_user
  get '/logout_store' => 'sessions#destroy_store', as: :logout_store

  match '/update_store', :to => 'stores#update', :via => [:patch], :as => :update_store
  match '/update_user', :to => 'users#update', :via => [:patch], :as => :update_user

  get '/api/loyard_id/:loyard_id/store/:api_key' => 'transactions#new', as: :new_transaction
  match '/changelocale', :to => 'application#change_locale', :via => [:post], :as => :changelocale

  get '/termsandconditions' => 'terms_and_conditions#show', as: :terms_and_conditions

end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password, :generate_api_key

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username, :email
  validates_uniqueness_of :email, :username

  has_many :transactions

  def self.authenticate (username,password)
    store = find_by_username(username)
    if store && password_matches?(store,password)
      store
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def generate_api_key
    if !self.api_key
      self.api_key = Digest::SHA1.hexdigest([Time.now, rand].join)
    end
  end

  private
  def self.password_matches?(store,password_supplied)
     store.password_hash == BCrypt::Engine.hash_secret(password_supplied, store.password_salt)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :require_store_login, :except => [:new, :create]
  def new
    @store = Store.new
  end

  def create
      @store = Store.new(store_params)
      if @store.save
        redirect_to root_url, :flash => { :success => t("success_message") }
      else
        render 'new'
      end
  end

  def show
    @store = current_store
  end

  def edit
    @store = current_store
  end

  def update
    @store = current_store
    if @store.update(edit_store_params)
      flash.now[:success] = t('update_successful')
    else
      flash.now[:info] = t('update_unsuccessful')
    end
    render 'edit'
  end

  private
  def store_params
    params[:store].permit(:number, :name, :phone, :address, :email, :city, :postal_code, :province, :country, :owner_name, :owner_phone, :owner_address, :owner_email, :owner_city, :owner_postal_code, :owner_province, :owner_country, :username, :password, :password_confirmation )
  end

  def edit_store_params
    params[:store].permit(:number, :name, :phone, :address, :email, :city, :postal_code, :province, :country, :owner_name, :owner_phone, :owner_address, :owner_email, :owner_city, :owner_postal_code, :owner_province, :owner_country, :password, :password_confirmation )
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/edit.html.erb
<div class="row col-lg-8 col-md-6 col-xs-10 col-lg-offset-2 col-md-offset-3 col-xs-offset-1">
	<% if @store.errors.any? %>
		<div class="alert alert-danger alert-dismissible" role="alert">
 			 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 			 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
 			 <strong>Oops!</strong>
 			  <% for message in @user.errors.full_messages %>
		  		<li><%= message %></li>
			  <% end %>
		</div>
	<% end %>
	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h4 class="panel-title"><%= t('update') %></h3>
  		</div>


	  	<div class="panel-body">
			<%= form_for @store, :url => update_store_path, :html => { :class => 'form-horizontal' } do |f| %>
				<p class="bg-primary" style="padding:5px 10px"><%= t('business_info') %></p>
					<div class="form-group">
							<%= f.label t('business_number') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :number , :class => 'form-control', :required => true %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('business_name') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :name , :class => 'form-control', :required => true %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('phone') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :phone , :class => 'form-control', :required => true, :type => "phone"  %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('address') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :address , :class => 'form-control', :required => true%>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('email') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :email , :class => 'form-control', :required => true %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('city') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :city , :class => 'form-control', :required => true %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('postal_code') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :postal_code , :class => 'form-control', :required => true %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('province') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :province , :class => 'form-control', :required => true %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('country') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :country , :class => 'form-control', :required => true %>
							</div>
					</div>

					<p class="bg-info" style="padding:5px 10px"><%= t('owner_info') %></p>

					<div class="form-group">
							<%= f.label t('name') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :owner_name , :class => 'form-control', :required => true %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('phone') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :owner_phone , :class => 'form-control', :required => true, :type => "phone"  %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('city') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :owner_city , :class => 'form-control', :required => true %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('postal_code') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :owner_postal_code , :class => 'form-control', :required => true %>
							</div>
					</div>

					<div class="form-group">
							<%= f.label t('province') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :owner_province , :class => 'form-control', :required => true %>
							</div>
					</div>
					<div class="form-group">
							<%= f.label t('country') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.text_field :owner_country , :class => 'form-control', :required => true %>
							</div>
					</div>
					<p class="bg-warning" style="padding:5px 10px"><%= t('login_info') %></p>

					<div class="form-group">
							<%= f.label t('password') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.password_field :password , :class => 'form-control'%>
							</div>
					</div>
					<div class="form-group">
							<%= f.label t('password_confirmation') , :class => 'col-sm-3 control-label' %>
							<div class="col-sm-9">
									<%= f.password_field :password_confirmation , :class => 'form-control' %>
							</div>
					</div>

			    <div class="form-group">
			        <div class="col-sm-offset-3 col-sm-9">
			            <%= submit_tag t('update') , :class => 'btn btn-primary' %>

			            <%= link_to t('cancel') , root_url, :class => 'btn btn-default' %>
			        </div>
			    </div>
			<% end %>
		</div>
  	</div>
</div>

app/views/stores/new.html.erb
<div class="row col-lg-8 col-md-6 col-xs-10 col-lg-offset-2 col-md-offset-3 col-xs-offset-1">
	<% if @store.errors.any? %>
		<div class="alert alert-danger alert-dismissible" role="alert">
 			 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 			 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
 			 <strong>Oops!</strong>
 			  <% for message in @user.errors.full_messages %>
		  		<li><%= message %></li>
			  <% end %>
		</div>
	<% end %>
	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h4 class="panel-title"><%= t('sign_up') %></h3>
  		</div>


	  	<div class="panel-body">
			<%= form_for @store, :html => { :class => 'form-horizontal' } do |f| %>
				<p class="bg-primary" style="padding:5px 10px"><%= t('business_info') %></p>
			    <div class="form-group">
			        <%= f.label t('business_number') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :number , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('business_name') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :name , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
              <%= f.label t('phone') , :class => 'col-sm-3 control-label' %>
              <div class="col-sm-9">
                  <%= f.text_field :phone , :class => 'form-control', :required => true, :type => "phone"  %>
              </div>
          </div>

			    <div class="form-group">
			        <%= f.label t('address') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :address , :class => 'form-control', :required => true%>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('email') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :email , :class => 'form-control', :required => true %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label t('city') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :city , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('postal_code') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :postal_code , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('province') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :province , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('country') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :country , :class => 'form-control', :required => true %>
			        </div>
			    </div>

					<p class="bg-info" style="padding:5px 10px"><%= t('owner_info') %></p>

          <div class="form-group">
			        <%= f.label t('name') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :owner_name , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('phone') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :owner_phone , :class => 'form-control', :required => true, :type => "phone"  %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('city') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :owner_city , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('postal_code') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :owner_postal_code , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('province') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :owner_province , :class => 'form-control', :required => true %>
			        </div>
			    </div>
          <div class="form-group">
			        <%= f.label t('country') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :owner_country , :class => 'form-control', :required => true %>
			        </div>
			    </div>
					<p class="bg-warning" style="padding:5px 10px"><%= t('login_info') %></p>

          <div class="form-group">
			        <%= f.label t('username') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :username , :class => 'form-control', :required => true %>
			        </div>
			    </div>
          <div class="form-group">
			        <%= f.label t('password') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password , :class => 'form-control', :required => true %>
			        </div>
			    </div>
          <div class="form-group">
			        <%= f.label t('password_confirmation') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password_confirmation , :class => 'form-control', :required => true %>
			        </div>
			    </div>

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<b><%= link_to "By registering, I agree to terms and conditions", terms_and_conditions_path %></b>
						</div>
					</div>


			    <div class="form-group">
			        <div class="col-sm-offset-3 col-sm-9">
			            <%= submit_tag t('register') , :class => 'btn btn-primary' %>

			            <%= link_to t('cancel'), root_url, :class => 'btn btn-default' %>
			        </div>
			    </div>
			<% end %>
		</div>
  	</div>
</div>

app/views/stores/show.html.erb
<div class="row col-xs-12">
  <h4 class="text-center"><%= t('api_key') %>: <kbd><%= @store.api_key %></kbd></h4>
  <br />
  <h3><%= t('how_to_use_api') %></h3>
  <ul>
    <li><%= t('how_to_use_api_step_1') %></li>
    <li><%= raw t('how_to_use_api_step_2') %></li>
      <ul>
        <li><%= raw t('how_to_use_api_step_2_1') %></li>
        <li><%= raw t('how_to_use_api_step_2_2') %></li>
      </ul>
  </ul>
  <br />
  <h5 class="text-muted"><%= t('how_does_response_look_like') %></h5>
  <ul>
    <li><%= raw t('how_does_response_look_like_step_1') %></li>
    <li><%= raw t('how_does_response_look_like_step_2') %><li>
        <pre>
          {
              "first_name": "John",
              "last_name": "Doe",
              "email": "john@doe.com",
              "phone": "1112221111",
              "date_of_birth": "1/11/1981,
              "address": "#1, Xyz St.",
              "city": "Xyz",
              "postal_code": "XXX YYY",
              "province": "XYZ",
              "country": "ABC"
            }
        </pre>
    <li><%= raw t('how_does_response_look_like_step_3') %></li>
      <pre>
        {
          "error": "error occured"
        }
      </pre>
  </ul>
</div>