config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  resources :users
  resources :stores

  match '/authenticate_user', :to => 'sessions#authenticate_user', :via => [:post], :as => :authenticate_user
  match '/authenticate_store', :to => 'sessions#authenticate_store', :via => [:post], :as => :authenticate_store

  get '/logout_user' => 'sessions#destroy_user', as: :logout_user
  get '/logout_store' => 'sessions#destroy_store', as: :logout_store

  match '/update_store', :to => 'stores#update', :via => [:patch], :as => :update_store
  match '/update_user', :to => 'users#update', :via => [:patch], :as => :update_user

  get '/api/loyard_id/:loyard_id/store/:api_key' => 'transactions#new', as: :new_transaction
  match '/changelocale', :to => 'application#change_locale', :via => [:post], :as => :changelocale

  get '/termsandconditions' => 'terms_and_conditions#show', as: :terms_and_conditions

end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :password, :fullname
    before_save :encrypt_password, :generate_loyard_id

    validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :first_name, :last_name, :username, :email
    validates_uniqueness_of :email, :username

    has_many :transactions

    def self.authenticate (username,password)
      user = find_by_username(username)
      if user && password_matches?(user,password)
        user
      end
    end

    def fullname
      "#{first_name} #{last_name}"
    end

    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end

    def generate_loyard_id
      if !self.loyard_id
        self.loyard_id = Time.now.year.to_s + self.id.to_s + self.first_name[0] + Time.now.day.to_s + self.last_name[0] +  Random.rand(11).to_s
      end
    end

    private
    def self.password_matches?(user,password_supplied)
       user.password_hash == BCrypt::Engine.hash_secret(password_supplied, user.password_salt)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_login, :except => [:new, :create]
  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
        redirect_to root_url, :flash => { :success => t('success_message') }
      else
        render 'new'
      end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(edit_user_params)
      flash.now[:success] = t('update_successful')
    else
      flash.now[:info] = t('update_unsuccessful')
    end
    render 'edit'
  end


  private
  def user_params
    params[:user].permit(:first_name, :last_name, :username, :password, :password_confirmation, :email, :phone, :date_of_birth, :address, :city, :postal_code, :province, :country )
  end

  def edit_user_params
    params[:user].permit(:first_name, :last_name, :password, :password_confirmation, :email, :phone, :date_of_birth, :address, :city, :postal_code, :province, :country )
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
<div class="row col-lg-8 col-md-6 col-xs-10 col-lg-offset-2 col-md-offset-3 col-xs-offset-1">
	<% if @user.errors.any? %>
		<div class="alert alert-danger alert-dismissible" role="alert">
 			 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 			 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
 			 <strong>Oops!</strong>
 			  <% for message in @user.errors.full_messages %>
		  		<li><%= message %></li>
			  <% end %>
		</div>
	<% end %>
	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h4 class="panel-title"><%= t('update') %></h4>
  		</div>

	  	<div class="panel-body">
			<%= form_for @user, :url => update_user_path, :html => { :class => 'form-horizontal' } do |f| %>
			    <div class="form-group">
			        <%= f.label t('first_name') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :first_name , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('last_name') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :last_name , :class => 'form-control', :required => true %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label t('password') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password , :class => 'form-control' %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label t('password_confirmation') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password_confirmation , :class => 'form-control' %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label t('email') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :email , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('phone') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :phone , :class => 'form-control', :required => true, :type => "phone" %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('date_of_birth') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :date_of_birth , :class => 'form-control', :required => true  %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('address') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :address , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('city') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :city , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('postal_code') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :postal_code , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('province') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :province , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('country') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :country , :class => 'form-control', :required => true %>
			        </div>
			    </div>


			    <div class="form-group">
			        <div class="col-sm-offset-3 col-sm-9">
			            <%= submit_tag t('update') , :class => 'btn btn-primary' %>

			            <%= link_to t('cancel'), root_url, :class => 'btn btn-default' %>
			        </div>
			    </div>
			<% end %>
		</div>
  	</div>
</div>

app/views/users/new.html.erb
<div class="row col-lg-8 col-md-6 col-xs-10 col-lg-offset-2 col-md-offset-3 col-xs-offset-1">
	<% if @user.errors.any? %>
		<div class="alert alert-danger alert-dismissible" role="alert">
 			 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 			 <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
 			 <strong>Oops!</strong>
 			  <% for message in @user.errors.full_messages %>
		  		<li><%= message %></li>
			  <% end %>
		</div>
	<% end %>
	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h4 class="panel-title"><%= t('sign_up') %></h4>
  		</div>

	  	<div class="panel-body">
			<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
			    <div class="form-group">
			        <%= f.label t('first_name') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :first_name , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('last_name') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :last_name , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
              <%= f.label t('username') , :class => 'col-sm-3 control-label' %>
              <div class="col-sm-9">
                  <%= f.text_field :username , :class => 'form-control', :required => true %>
              </div>
          </div>

			    <div class="form-group">
			        <%= f.label t('password') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password , :class => 'form-control', :required => true%>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label t('password_confirmation') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.password_field :password_confirmation , :class => 'form-control', :required => true %>
			        </div>
			    </div>

			    <div class="form-group">
			        <%= f.label t('email') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :email , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('phone') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :phone , :class => 'form-control', :required => true, :type => "phone" %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('date_of_birth') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :date_of_birth , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('address') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :address , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('city') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :city , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('postal_code') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :postal_code , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('province') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :province , :class => 'form-control', :required => true %>
			        </div>
			    </div>

          <div class="form-group">
			        <%= f.label t('country') , :class => 'col-sm-3 control-label' %>
			        <div class="col-sm-9">
			            <%= f.text_field :country , :class => 'form-control', :required => true %>
			        </div>
			    </div>

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<b><%= link_to "By registering, I agree to terms and conditions", terms_and_conditions_path %></b>
						</div>
					</div>

			    <div class="form-group">
			        <div class="col-sm-offset-3 col-sm-9">
			            <%= submit_tag t('register') , :class => 'btn btn-primary' %>

			            <%= link_to t('cancel'), root_url, :class => 'btn btn-default' %>
			        </div>
			    </div>
			<% end %>
		</div>
  	</div>
</div>

app/views/users/show.html.erb
<div class="col-xs-12">
  <h3> <%= t('your_loyard_id') %> <kbd><%= @user.loyard_id %></kbd></h3>
  <br />
  <% if @user.transactions.any? %>
  <table class="table table-striped">
    <thead>
        <tr>
          <th><%= t('date') %></th>
          <th><%= t('business_name') %></th>
          <th><%= t('address') %></th>
        </tr>
    </thead>
    <tbody>
      <% @user.transactions.each do |t| %>
      <tr>
        <td><%= t.created_at.to_formatted_s(:long) %></td>
        <td><%= t.store.name %></td>
        <td><%= t.store.address %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <div class="well">
        <h3 class="text-center"><%= t('no_transactions_to_show') %></h3>
    </div>
  <% end %>
</div>