config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  resources :users
  resources :stores

  match '/authenticate_user', :to => 'sessions#authenticate_user', :via => [:post], :as => :authenticate_user
  match '/authenticate_store', :to => 'sessions#authenticate_store', :via => [:post], :as => :authenticate_store

  get '/logout_user' => 'sessions#destroy_user', as: :logout_user
  get '/logout_store' => 'sessions#destroy_store', as: :logout_store

  match '/update_store', :to => 'stores#update', :via => [:patch], :as => :update_store
  match '/update_user', :to => 'users#update', :via => [:patch], :as => :update_user

  get '/api/loyard_id/:loyard_id/store/:api_key' => 'transactions#new', as: :new_transaction
  match '/changelocale', :to => 'application#change_locale', :via => [:post], :as => :changelocale

  get '/termsandconditions' => 'terms_and_conditions#show', as: :terms_and_conditions

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "sans-nav"
  def index
    if current_user
      redirect_to user_path(current_user)
    elsif current_store
      redirect_to store_path(current_store)
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
 <div class="col-xs-10 col-xs-offset-1">
    <h1 class="text-center"><%= t('welcome') %></h1>
    <h3 class="text-center muted"><%= t('subheading') %></h3>
    <br />
</div>

<div class="col-xs-12 row">
    <div id="tabs" class="tabs">
      <nav>
        <ul>
          <li><a href="#section-1"><span><i class="material-icons v-middle">face</i><%= t('user') %></span></a></li>
          <li><a href="#section-2"><span><i class="material-icons v-middle">store</i><%= t('store') %></span></a></li>
        </ul>
      </nav>
      <div class="content">
        <section id="section-1">
            <div class="row col-md-6 col-xs-10 col-md-offset-3 col-xs-offset-1">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title"><%= t('login') %></h4>
                </div>
                <div class="panel-body">
                  <%= form_tag authenticate_user_path , { :class => 'form-horizontal' , :role => 'form' } do %>
                  <div class="form-group">
                    <%= label_tag :username, raw("<i class='material-icons v-middle'>account_circle</i>") , :class => 'col-sm-2 control-label' %>
                    <div class="col-sm-10">
                      <%= text_field_tag :username , params[:username] , :class => 'form-control', :required => true, :placeholder => t("username") %>
                    </div>
                  </div>

                  <div class="form-group">
                    <%= label_tag :password, raw("<i class='material-icons v-middle'>vpn_key</i>"), :class => 'col-sm-2 control-label' %>
                    <div class="col-sm-10">
                      <%= password_field_tag :password , nil , :class => 'form-control', :required => true, :placeholder => t('password') %>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <%= button_tag(type: 'submit', class: "btn btn-warning") do %>
                      <%= t('login') %>
                      <% end %>
                    </div>
                  </div>
                  <% end %>
                  <p class="text-center text-muted special-link"><%= link_to t('sign_up_user'), new_user_path %></p>


                </div>
              </div>
            </div>
        </section>
        <section id="section-2">
              <div class="row col-md-6 col-xs-10 col-md-offset-3 col-xs-offset-1">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title"><%= t('login') %></h4>
                  </div>
                  <div class="panel-body">
                    <%= form_tag authenticate_store_path , { :class => 'form-horizontal' , :role => 'form' } do %>
                    <div class="form-group">
                      <%= label_tag :username, raw("<i class='material-icons v-middle'>account_circle</i>"), :class => 'col-sm-2 control-label' %>
                      <div class="col-sm-10">
                        <%= text_field_tag :username , params[:username] , :class => 'form-control', :required => true, :placeholder => t('username') %>
                      </div>
                    </div>

                    <div class="form-group">
                      <%= label_tag :password, raw("<i class='material-icons v-middle'>vpn_key</i>"), :class => 'col-sm-2 control-label' %>
                      <div class="col-sm-10">
                        <%= password_field_tag :password , nil , :class => 'form-control', :required => true, :placeholder => t('password') %>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-10">
                        <%= button_tag(type: 'submit', class: "btn btn-warning") do %>
                        <%= t('login') %>
                        <% end %>
                      </div>
                    </div>
                    <% end %>
                    <p class="text-center text-muted special-link""><%= link_to t('sign_up_store'), new_store_path %></p>
                  </div>
                </div>
              </div>
        </section>
      </div><!-- /content -->
    </div><!-- /tabs -->
</div>