config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  resources :users
  resources :stores

  match '/authenticate_user', :to => 'sessions#authenticate_user', :via => [:post], :as => :authenticate_user
  match '/authenticate_store', :to => 'sessions#authenticate_store', :via => [:post], :as => :authenticate_store

  get '/logout_user' => 'sessions#destroy_user', as: :logout_user
  get '/logout_store' => 'sessions#destroy_store', as: :logout_store

  match '/update_store', :to => 'stores#update', :via => [:patch], :as => :update_store
  match '/update_user', :to => 'users#update', :via => [:patch], :as => :update_user

  get '/api/loyard_id/:loyard_id/store/:api_key' => 'transactions#new', as: :new_transaction
  match '/changelocale', :to => 'application#change_locale', :via => [:post], :as => :changelocale

  get '/termsandconditions' => 'terms_and_conditions#show', as: :terms_and_conditions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loyard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id="<%= controller_name %>" class="<%= action_name %>">

  <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Loyard", root_path, :class => "navbar-brand" %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span style="vertical-align:bottom"><%= current_user.fullname %></span>
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t('edit'), edit_user_path(current_user) %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to t('logout'), logout_user_path %></li>
                  </ul>
              </li>
            <% end %>

            <% if current_store %>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span style="vertical-align:bottom"><%= current_store.owner_name %></span>
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t('edit'), edit_store_path(current_store) %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to t('logout'), logout_store_path %></li>
                  </ul>
              </li>
            <% end %>

          </ul>
        </div><!-- /.container-fluid -->
  </nav>
  <div class="container">

    <div class="row col-md-6 col-sm-10 col-md-offset-3 col-sm-offset-1">
            <% flash.each do |k, v| %>
                <div class="alert alert-<%= k %> text-center alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= v %></div>
         <% end %>
       </div>
    <%= yield %>
  </div>
  <div class="box">
    <%= link_to "English", "#", :class => "change_locale", :'data-locale' => 'en' %> | <%= link_to "Français", "#", :class => "change_locale", :'data-locale' => 'fr' %>
  </div>
</body>
</html>

app/views/layouts/sans-nav.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loyard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id="<%= controller_name %>" class="<%= action_name %>">
  <div class="container">

    <div class="row col-md-6 col-sm-10 col-md-offset-3 col-sm-offset-1">
            <% flash.each do |k, v| %>
                <div class="alert alert-<%= k %> text-center alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= v %></div>
         <% end %>
       </div>
    <%= yield %>
  </div>
  <div class="box">
    <%= link_to "English", "#", :class => "change_locale", :'data-locale' => 'en' %> | <%= link_to "Français", "#", :class => "change_locale", :'data-locale' => 'fr' %>
  </div>
</body>
</html>